CREATE OR REPLACE PROCEDURE drop_user(
    user_name NVARCHAR2
) 
IS
    li_count NUMBER;
BEGIN
    SELECT COUNT (1)
    INTO li_count
    FROM dba_users
   	WHERE username = UPPER ( user_name );

   	IF li_count != 0
   	THEN
		EXECUTE IMMEDIATE ( 'DROP USER '|| user_name || ' CASCADE' );
    END IF;
END;
/


CREATE OR REPLACE PROCEDURE create_user(
	user_name NVARCHAR2,
	pwd NVARCHAR2
) IS
    li_count NUMBER;
BEGIN
    SELECT COUNT (1)
    INTO li_count
    FROM dba_users
   	WHERE username = UPPER ( user_name );

   	IF li_count = 0
   	THEN
        EXECUTE IMMEDIATE ( 'CREATE USER ' || user_name || ' IDENTIFIED BY ' || pwd || ' DEFAULT TABLESPACE SYSTEM' );    
    END IF;
END;
/

EXEC create_user('C##QLYT','lamhoangphuc');

-- gran quyen de tao cac table
GRANT create session TO C##QLYT;
GRANT create table TO C##QLYT;
GRANT create view TO C##QLYT;
GRANT create any trigger TO C##QLYT;
GRANT create any procedure TO C##QLYT;
GRANT create sequence TO C##QLYT;
GRANT create synonym TO C##QLYT;


CREATE TABLE C##QLYT.CSYT (
    MACSYT VARCHAR2(5) NOT NULL,
    TENCSYT NVARCHAR2(100) NOT NULL,
    DCCSYT NVARCHAR2(300) NOT NULL,
    SDTCSYT NVARCHAR2(20) NOT NULL,

    CONSTRAINT CSYT_PK PRIMARY KEY (MACSYT)
);

CREATE TABLE C##QLYT.BENHNHAN (
    MABN VARCHAR2(10) NOT NULL,
    MACSYT VARCHAR2(5) NOT NULL,

    TENBN NVARCHAR2(100) NOT NULL,
    CMND NVARCHAR2(20) NOT NULL,
    NGAYSINH DATE NOT NULL,
    SONHA VARCHAR2(20) NOT NULL,
    TENDUONG NVARCHAR2(100) NOT NULL,
    QUANHUYEN NVARCHAR2(100) NOT NULL,
    TINHTP NVARCHAR2(100) NOT NULL,
    TIENSUBENH NVARCHAR2(500) NOT NULL,
    TIENSUBENHGD NVARCHAR2(500) NOT NULL,
    DIUNGTHUOC NVARCHAR2(254) NOT NULL,

    CONSTRAINT BN_PK PRIMARY KEY (MABN),
    CONSTRAINT BN_TO_CSYT_FK FOREIGN KEY (MACSYT) REFERENCES C##QLYT.CSYT(MACSYT)
);

CREATE TABLE C##QLYT.NHANVIEN (
    MANV VARCHAR2(10) NOT NULL,
    HOTEN NVARCHAR2(100) NOT NULL,

    PHAI NVARCHAR2(10) NOT NULL,
    CMND NVARCHAR2(20) NOT NULL,
    NGAYSINH DATE NOT NULL,

    QUEQUAN NVARCHAR2(300) NOT NULL,
    SODTH VARCHAR2(20) NOT NULL,

    CSYT VARCHAR2(5) NOT NULL,
    VAITRO NVARCHAR2(50) NOT NULL,
    CHUYENKHOA NVARCHAR2(254) NOT NULL,

    CONSTRAINT NV_PK PRIMARY KEY (MANV),
    CONSTRAINT NV_TO_CSYT_FK FOREIGN KEY (CSYT) REFERENCES C##QLYT.CSYT(MACSYT)
);