CREATE OR REPLACE PROCEDURE drop_user_if_exists (user_name VARCHAR2)
AS n NUMBER;
BEGIN
    n := 0;
    SELECT COUNT(*) INTO n FROM dba_users WHERE USERNAME = UPPER(user_name);
    IF (n != 0) THEN
        DBMS_OUTPUT.PUT_LINE('User ' || user_name || ' da ton tai'); 
        EXECUTE IMMEDIATE ('DROP USER '|| user_name || ' CASCADE');
    END IF;
END;
/
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
EXEC drop_user_if_exists('QLKCB');

CREATE USER QLKCB IDENTIFIED BY 123456;
ALTER USER QLKCB quota 20M ON USERS;

GRANT ALL PRIVILEGES TO QLKCB;
GRANT SELECT ANY DICTIONARY TO QLKCB;
--GRANT CREATE TABLE TO QLKCB;
--GRANT CREATE ANY PROCEDURE, ALTER ANY PROCEDURE, EXECUTE ANY PROCEDURE, DROP ANY PROCEDURE TO QLKCB;
--GRANT CREATE ANY TRIGGER TO QLKCB;
--GRANT CREATE ANY VIEW TO QLKCB;
--GRANT GRANT ANY ROLE TO QLKCB;
--GRANT CREATE USER TO QLKCB;
--GRANT GRANT ANY OBJECT PRIVILEGE TO QLKCB;



-- Connect vao user C##PH2 de tao bang thay vi tao bang co ten C##PH2.HSBA
CONNECT QLKCB/123456;

-- Tao bang KHOA
CREATE TABLE KHOA (
    MAKHOA VARCHAR(10) PRIMARY KEY,
    TENKHOA NVARCHAR2(100) NOT NULL UNIQUE
);

-- Tao bang DICHVU
CREATE TABLE DICHVU (
    MADV VARCHAR2(5) PRIMARY KEY,
    TENDV NVARCHAR2(100) NOT NULL UNIQUE
);

-- Tao bang CSYT
CREATE TABLE CSYT (
    MACSYT VARCHAR2(4) PRIMARY KEY,
    TENCSYT NVARCHAR2(100) NOT NULL,
    DCCSYT NVARCHAR2(200) NOT NULL,
    SDTCSYT VARCHAR2(15) NOT NULL
);

-- Tao bang BENHNHAN
CREATE TABLE BENHNHAN (
    MABN VARCHAR2(7) PRIMARY KEY,
    TENBN NVARCHAR2(100) NOT NULL,
    MACSYT VARCHAR2(4) NOT NULL,
    CMND VARCHAR2(15) UNIQUE,
    NGAYSINH DATE NOT NULL,
    SONHA VARCHAR2(20),
    TENDUONG NVARCHAR2(100),
    QUANHUYEN NVARCHAR2(100) NOT NULL,
    TINHTP NVARCHAR2(100) NOT NULL,
    TIENSUBENH NVARCHAR2(200),
    TIENSUBENHGD NVARCHAR2(200),
    DIUNGTHUOC NVARCHAR2(200),
    USERNAME VARCHAR2(128) NOT NULL,

    CONSTRAINT FK_BENHNHAN_MACSYT_CSYT FOREIGN KEY (MACSYT) REFERENCES CSYT(MACSYT)
);

-- Tao bang NHANVIEN
CREATE TABLE NHANVIEN (
    MANV VARCHAR2(6) PRIMARY KEY,
    HOTEN NVARCHAR2(100) NOT NULL,
    PHAI NVARCHAR2(5) NOT NULL,
    CMND VARCHAR2(15) NOT NULL UNIQUE,
    NGAYSINH DATE NOT NULL,
    QUEQUAN NVARCHAR2(200) NOT NULL,
    SODT VARCHAR2(15) NOT NULL,
    CSYT VARCHAR2(4) NOT NULL,
    VAITRO NVARCHAR2(20) NOT NULL,
    CHUYENKHOA VARCHAR2(10),
    USERNAME VARCHAR2(128) NOT NULL,

    CONSTRAINT FK_NHANVIEN_CSYT_CSYT FOREIGN KEY (CSYT) REFERENCES CSYT(MACSYT),
    CONSTRAINT FK_NHANVIEN_CHUYENKHOA_KHOA FOREIGN KEY (CHUYENKHOA) REFERENCES KHOA(MAKHOA)
);

-- Tao bang HSBA
CREATE TABLE HSBA (
    MAHSBA VARCHAR2(8) PRIMARY KEY,
    MABN VARCHAR2(7) NOT NULL,
    NGAY DATE NOT NULL,
    CHANDOAN NVARCHAR2(200),
    MABS VARCHAR2(6) NOT NULL,
    MAKHOA VARCHAR2(10) NOT NULL,
    MACSYT VARCHAR2(4) NOT NULL,
    KETLUAN NVARCHAR2(200),
    
    CONSTRAINT FK_HSBA_MABN_BENHNHAN FOREIGN KEY (MABN) REFERENCES BENHNHAN(MABN)
    CONSTRAINT FK_HSBA_MABS_NHANVIEN FOREIGN KEY (MABS) REFERENCES NHANVIEN(MANV),
    CONSTRAINT FK_HSBA_MACSYT_CSYT FOREIGN KEY (MACSYT) REFERENCES CSYT(MACSYT),
    CONSTRAINT FK_HSBA_MAKHOA_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
);

-- Tao bang HSBA_DV 
CREATE TABLE HSBA_DV (
    MAHSBA VARCHAR2(8),
    MADV VARCHAR2(5),
    NGAY DATE,
    MAKTV VARCHAR2(6) NOT NULL,
    KETQUA NVARCHAR2(200),
    
    CONSTRAINT PK_HSBADV PRIMARY KEY (MAHSBA, MADV, NGAY),
    CONSTRAINT FK_HSBADV_MAHSBA_HSBA FOREIGN KEY (MAHSBA) REFERENCES HSBA(MAHSBA),
    CONSTRAINT FK_HSBADV_MADV_DICHVU FOREIGN KEY (MADV) REFERENCES DICHVU(MADV),
    CONSTRAINT FK_HSBADV_MAKTV_NHANVIEN FOREIGN KEY (MAKTV) REFERENCES NHANVIEN(MANV)
);

INSERT INTO CSYT VALUES ('CS01', 'Co so 1', 'Quan 8, TPHCM', '123456789');
INSERT INTO CSYT VALUES ('CS02', 'Co so 2', 'Quan 5, TPHCM', '098765764');
INSERT INTO CSYT VALUES ('CS03', 'Co so 3', 'Quan 1, TPHCM', '098765233');

INSERT INTO NHANVIEN VALUES ('NV0001', 'Nguyen Van A', 'Nam', '12345678', To_DATE('1990/02/02', 'yyyy/mm/dd'), 'TPHCM', '123456789', 'CS01', 'Thanh tra', 'Tim', 'NV0001');
INSERT INTO NHANVIEN VALUES ('NV0002', 'Nguyen Thi B', 'Nu', '414125353', To_DATE('1990/07/05', 'yyyy/mm/dd'), 'TPHCM', '123456789', 'CS01', 'Thanh tra', 'Tim', 'NV0002');
INSERT INTO NHANVIEN VALUES ('NV0003', 'Nguyen Van C', 'Nam', '746463452', To_DATE('1990/03/02', 'yyyy/mm/dd'), 'TPHCM', '123456789', 'CS01', 'Bac si', 'Tim', 'NV0003');
INSERT INTO NHANVIEN VALUES ('NV0004', 'Nguyen Van D', 'Nam', '746235452', To_DATE('1990/03/02', 'yyyy/mm/dd'), 'TPHCM', '098765434', 'CS01', 'Co so y te', 'Tim', 'NV0004');
INSERT INTO NHANVIEN VALUES ('NV0005', 'Nguyen Van E', 'Nam', '767524374', To_DATE('1990/03/02', 'yyyy/mm/dd'), 'TPHCM', '098765233', 'CS02', 'Co so y te', 'Tim', 'NV0005');

INSERT INTO KHOA VALUES ('K001', 'Khoa Phu san');
INSERT INTO KHOA VALUES ('K002', 'Khoa Nhi');
INSERT INTO KHOA VALUES ('K003', 'Khoa Truyen nhiem');
INSERT INTO KHOA VALUES ('K004', 'Khoa Cap cuu');

INSERT INTO DICHVU VALUES ('DV001', 'Xet nghiem mau');
INSERT INTO DICHVU VALUES ('DV002', 'Chup hinh X quang');
INSERT INTO DICHVU VALUES ('DV003', 'Test Covid');
INSERT INTO DICHVU VALUES ('DV004', 'Xet nghiem nuoc tieu');

INSERT INTO BENHNHAN VALUES ('BN00001', 'Lam Hoang Phuc', 'CS01', '12132244', To_DATE('2001/03/02', 'yyyy/mm/dd'), '', '', 'Quan 1', 'HCM', '', '', '', 'BN00001');
INSERT INTO BENHNHAN VALUES ('BN00002', 'Ho Nhat Linh', 'CS01', '12132554', To_DATE('2001/05/02', 'yyyy/mm/dd'), '', '', 'Quan 3', 'HCM', '', '', '', 'BN00002');
INSERT INTO BENHNHAN VALUES ('BN00003', 'Nguyen Van Linh', 'CS02', '113224534', To_DATE('2001/10/02', 'yyyy/mm/dd'), '', '', 'Quan 1', 'HCM', '', '', '', 'BN00003');
INSERT INTO BENHNHAN VALUES ('BN00004', 'Lam Lo', 'CS02', '121322644', To_DATE('2001/03/02', 'yyyy/mm/dd'), '', '', 'Quan 1', 'HCM', '', '', '', 'BN00004');



COMMIT;
